[package]
authors = ["Mohamed Faizaan"]
license = "MIT"
description = "Part of the TaintFlow static application security testing (SAST) engine."
repository = "https://github.com/MohamedFaizaan/TaintFlow"
homepage = "https://github.com/MohamedFaizaan/TaintFlow"
documentation = "https://docs.rs/taintflow"
name = "features"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
normalizer = { path = "../normalizer" }
symbols = { path = "../symbols" }
cfg = { path = "../cfg" }
taint = { path = "../taint" }
rules = { path = "../rules" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
